'use strict';
const $=id=>document.getElementById(id);let token='',timer=null,data=null,loading=false;
const number=v=>v==null?'—':Number(v).toLocaleString('es-CL',{maximumFractionDigits:1});
const percent=v=>v==null?'—':number(v*100)+'%';
const reasons={harness_fail:'El modelo incumple casos del harness.',quality_unknown:'No hay evidencia suficiente de calidad.',no_traffic:'Sin tráfico para evaluar los SLO.',slo_degraded:'Uno o más SLO están fuera del umbral.',schema_or_contract_drift:'Se detectó una respuesta o contrato inválido.',pin_quality_contract_or_readiness:'Revisar versión activa, evidencia, contrato y disponibilidad.',shadow:'Modo shadow declarado.',canary:'Modo canary declarado.'};
function cell(row,text){const td=document.createElement('td');td.textContent=text;row.append(td);return td;}
function small(parent,text){const s=document.createElement('small');s.textContent=text;parent.append(s);}
function error(e){$('error').textContent=e.message;$('error').hidden=false;$('connection').textContent='Sin actualización · datos anteriores';}
async function api(path){const r=await fetch(path,{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(r.status===401?'Token inválido o caducado. Sal y vuelve a conectar.':'Consulta fallida: HTTP '+r.status);return r.json();}
function selected(){return $('brain').value;}
function draw(){if(!data)return;const bid=selected();const metric=bid?data.by_brain[bid]:data.summary;const m=metric||{total:0,rejected:0,p95_ms:null,review_rate:null,buckets:[]};$('total').textContent=number(m.total);$('rejects').textContent=number(m.rejected);$('latency').textContent=m.p95_ms==null?'—':number(m.p95_ms)+' ms';$('review').textContent=percent(m.review_rate);chart(m.buckets);
 $('consumerstatus').textContent=!data.consumer?.configured?'Consumidor no configurado.':data.consumer.alive?'Consumidor activo. Entregas persistentes; los errores definitivos requieren revisión.':'Sin señal reciente del consumidor: revisar proceso y registros.';
 $('deliveries').replaceChildren();for(const d of (data.deliveries||[]).filter(d=>!bid||d.brain_id===bid)){const row=document.createElement('tr');small(cell(row,d.route_id),d.brain_id+' · '+(d.version||'sin versión fijada'));cell(row,{pending:'Pendiente',delivered:'Entregada',dead:'Requiere revisión'}[d.state]||d.state);cell(row,d.attempts);cell(row,d.error||d.result_id||'En espera');$('deliveries').append(row);}
 $('operations').replaceChildren();for(const o of data.operations.filter(o=>!bid||o.brain_id===bid)){const row=document.createElement('tr');small(cell(row,o.brain_id),o.version||'Sin versión verificable');const badge=document.createElement('span');badge.className='badge '+o.color;badge.textContent={green:'VERDE',yellow:'AMARILLO',red:'ROJO'}[o.color];cell(row,'').append(badge);cell(row,{pass:'Aprobado',fail:'Fallido',unknown:'Sin evidencia'}[o.quality]||o.quality);cell(row,o.p95_ms==null?'—':number(o.p95_ms)+' ms');cell(row,percent(o.review_rate)+' / '+percent(o.fallback_rate));cell(row,o.reasons.map(r=>reasons[r]||r).join(' ')||'Cumple los controles observados.');$('operations').append(row);}
 $('decisions').replaceChildren();const decisions=data.decisions.filter(d=>!bid||d.brain_id===bid);for(const d of decisions){const row=document.createElement('tr');small(cell(row,new Date(d.timestamp*1000).toLocaleTimeString('es-CL')),d.brain_id+' · '+d.model_version);cell(row,d.action);cell(row,d.needs_review?'Sí':'No');const rc=cell(row,d.routing_rule);small(rc,'Confianza máxima por cabeza: '+Object.entries(d.probabilities).map(([k,p])=>k+' '+percent(Math.max(...Object.values(p)))).join(' · '));rc.title=JSON.stringify(d.routing_evidence);const button=document.createElement('button');button.textContent=d.trace_id.slice(0,12)+'…';button.onclick=()=>showTrace(d.trace_id);cell(row,'').append(button);$('decisions').append(row);}if(!decisions.length){const row=document.createElement('tr');const td=cell(row,'Sin decisiones para este filtro en la última hora.');td.colSpan=5;$('decisions').append(row);}}
function chart(buckets){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 960 180');svg.setAttribute('role','img');svg.setAttribute('aria-label','Solicitudes aceptadas y rechazadas por minuto durante la última hora');const maximum=Math.max(1,...buckets.map(b=>b.accepted+b.rejected));function rect(x,y,w,h,color){const r=document.createElementNS(ns,'rect');for(const [k,v] of Object.entries({x,y,width:w,height:h,fill:color}))r.setAttribute(k,v);svg.append(r);}function text(x,y,t){const e=document.createElementNS(ns,'text');e.setAttribute('x',x);e.setAttribute('y',y);e.textContent=t;svg.append(e);}text(0,14,maximum+' solicitudes/min');rect(35,150,915,1,'#dce5eb');buckets.forEach((b,i)=>{const a=125*b.accepted/maximum,r=125*b.rejected/maximum;rect(40+i*15,150-a,10,a,'#1769df');rect(40+i*15,150-a-r,10,r,'#dc7840');});text(35,174,'Hace 60 min');text(455,174,'Hace 30 min');text(915,174,'Ahora');$('chart').replaceChildren(svg);}
async function refresh(){if(!token||loading)return;loading=true;const session=token;try{const received=await api('/v1/dashboard');if(token!==session)return;data=received;const previous=selected();$('brain').replaceChildren(new Option('Todos los cerebros',''));for(const o of data.operations)$('brain').add(new Option(o.brain_id,o.brain_id));if([...$('brain').options].some(o=>o.value===previous))$('brain').value=previous;draw();$('dashboard').hidden=false;$('login').hidden=true;$('logout').hidden=false;$('refresh').hidden=false;$('connection').textContent='Conectado';$('updated').textContent='Actualizado '+new Date(data.generated_at*1000).toLocaleTimeString('es-CL');$('error').hidden=true;}catch(e){error(e);}finally{loading=false;}}
async function showTrace(id){$('traceid').value=id;try{const t=await api('/v1/traces/'+encodeURIComponent(id));const out=$('traceview');out.replaceChildren();if(!t.spans.length){out.textContent='Sin spans disponibles: puede haber muestreo, retención vencida o una ruta de almacenamiento distinta.';return;}const start=Math.min(...t.spans.map(s=>s.start_ns)),end=Math.max(...t.spans.map(s=>s.end_ns)),duration=Math.max(1,end-start);const title=document.createElement('p');title.textContent='Traza '+id+' · '+number(duration/1e6)+' ms'+(t.truncated?' · resultado limitado a 1000 spans':'');out.append(title);for(const s of t.spans){const item=document.createElement('div');item.className='traceitem';const label=document.createElement('div');label.className='label';label.textContent=s.service+' / '+s.name;small(label,s.status+' · '+number((s.end_ns-s.start_ns)/1e6)+' ms');item.append(label);const track=document.createElement('div');track.className='track';const bar=document.createElement('div');bar.className='bar';bar.style.marginLeft=(s.start_ns-start)/duration*100+'%';bar.style.width=(s.end_ns-s.start_ns)/duration*100+'%';track.append(bar);item.append(track);out.append(item);const detail=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='Span '+s.span_id+' · padre '+(s.parent_id||'ninguno');pre.textContent=JSON.stringify(s.attributes,null,2);detail.append(summary,pre);out.append(detail);}out.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){error(e);}}
$('login').onsubmit=e=>{e.preventDefault();token=$('token').value.trim();$('token').value='';refresh();clearInterval(timer);timer=setInterval(refresh,5000);};$('logout').onclick=()=>{token='';data=null;clearInterval(timer);$('dashboard').hidden=true;$('login').hidden=false;$('logout').hidden=true;$('refresh').hidden=true;$('connection').textContent='Sin conectar';$('error').hidden=true;};$('refresh').onclick=refresh;$('brain').onchange=draw;$('traceform').onsubmit=e=>{e.preventDefault();showTrace($('traceid').value.trim());};$('traces').onclick=async()=>{try{const d=await api('/v1/traces');$('tracelist').replaceChildren();for(const t of d.traces){const b=document.createElement('button');b.textContent=t.trace_id.slice(0,12)+' · '+t.spans+' spans'+(t.error?' · ERROR':'');b.onclick=()=>showTrace(t.trace_id);$('tracelist').append(b);}if(!d.traces.length)$('tracelist').textContent='Sin trazas registradas en la última hora.';}catch(e){error(e);}};
const params=new URLSearchParams(location.hash.slice(1));const initial=params.get('token');if(initial){history.replaceState(null,'',location.pathname);token=initial;refresh();timer=setInterval(refresh,5000);}
